// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sever.Models;

#nullable disable

namespace Sever.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240629172427_updateSchema")]
    partial class updateSchema
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Sever.Models.Actor", b =>
                {
                    b.Property<int>("ActorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActorId"), 1L, 1);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DoB")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ActorId");

                    b.ToTable("Actors");

                    b.HasData(
                        new
                        {
                            ActorId = 1,
                            DateCreated = new DateTime(2024, 6, 30, 0, 24, 27, 129, DateTimeKind.Local).AddTicks(3320),
                            DateUpdated = new DateTime(2024, 6, 30, 0, 24, 27, 129, DateTimeKind.Local).AddTicks(3321),
                            DoB = new DateTime(1965, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Robert Downey Jr.",
                            Nationality = "American"
                        },
                        new
                        {
                            ActorId = 2,
                            DateCreated = new DateTime(2024, 6, 30, 0, 24, 27, 129, DateTimeKind.Local).AddTicks(3326),
                            DateUpdated = new DateTime(2024, 6, 30, 0, 24, 27, 129, DateTimeKind.Local).AddTicks(3326),
                            DoB = new DateTime(1984, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Scarlett Johansson",
                            Nationality = "American"
                        },
                        new
                        {
                            ActorId = 3,
                            DateCreated = new DateTime(2024, 6, 30, 0, 24, 27, 129, DateTimeKind.Local).AddTicks(3327),
                            DateUpdated = new DateTime(2024, 6, 30, 0, 24, 27, 129, DateTimeKind.Local).AddTicks(3328),
                            DoB = new DateTime(1974, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Leonardo DiCaprio",
                            Nationality = "American"
                        },
                        new
                        {
                            ActorId = 4,
                            DateCreated = new DateTime(2024, 6, 30, 0, 24, 27, 129, DateTimeKind.Local).AddTicks(3329),
                            DateUpdated = new DateTime(2024, 6, 30, 0, 24, 27, 129, DateTimeKind.Local).AddTicks(3329),
                            DoB = new DateTime(1990, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Jennifer Lawrence",
                            Nationality = "American"
                        },
                        new
                        {
                            ActorId = 5,
                            DateCreated = new DateTime(2024, 6, 30, 0, 24, 27, 129, DateTimeKind.Local).AddTicks(3330),
                            DateUpdated = new DateTime(2024, 6, 30, 0, 24, 27, 129, DateTimeKind.Local).AddTicks(3330),
                            DoB = new DateTime(1954, 12, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Denzel Washington",
                            Nationality = "American"
                        },
                        new
                        {
                            ActorId = 6,
                            DateCreated = new DateTime(2024, 6, 30, 0, 24, 27, 129, DateTimeKind.Local).AddTicks(3331),
                            DateUpdated = new DateTime(2024, 6, 30, 0, 24, 27, 129, DateTimeKind.Local).AddTicks(3331),
                            DoB = new DateTime(1981, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Natalie Portman",
                            Nationality = "Israeli-American"
                        },
                        new
                        {
                            ActorId = 7,
                            DateCreated = new DateTime(2024, 6, 30, 0, 24, 27, 129, DateTimeKind.Local).AddTicks(3332),
                            DateUpdated = new DateTime(2024, 6, 30, 0, 24, 27, 129, DateTimeKind.Local).AddTicks(3332),
                            DoB = new DateTime(1956, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Tom Hanks",
                            Nationality = "American"
                        },
                        new
                        {
                            ActorId = 8,
                            DateCreated = new DateTime(2024, 6, 30, 0, 24, 27, 129, DateTimeKind.Local).AddTicks(3333),
                            DateUpdated = new DateTime(2024, 6, 30, 0, 24, 27, 129, DateTimeKind.Local).AddTicks(3334),
                            DoB = new DateTime(1990, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Emma Watson",
                            Nationality = "British"
                        },
                        new
                        {
                            ActorId = 9,
                            DateCreated = new DateTime(2024, 6, 30, 0, 24, 27, 129, DateTimeKind.Local).AddTicks(3335),
                            DateUpdated = new DateTime(2024, 6, 30, 0, 24, 27, 129, DateTimeKind.Local).AddTicks(3335),
                            DoB = new DateTime(1963, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Brad Pitt",
                            Nationality = "American"
                        },
                        new
                        {
                            ActorId = 10,
                            DateCreated = new DateTime(2024, 6, 30, 0, 24, 27, 129, DateTimeKind.Local).AddTicks(3336),
                            DateUpdated = new DateTime(2024, 6, 30, 0, 24, 27, 129, DateTimeKind.Local).AddTicks(3336),
                            DoB = new DateTime(1985, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Gal Gadot",
                            Nationality = "Israeli"
                        });
                });

            modelBuilder.Entity("Sever.Models.Director", b =>
                {
                    b.Property<int>("DirectorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DirectorId"), 1L, 1);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DoB")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DirectorId");

                    b.ToTable("Directors");

                    b.HasData(
                        new
                        {
                            DirectorId = 1,
                            DateCreated = new DateTime(2024, 6, 30, 0, 24, 27, 129, DateTimeKind.Local).AddTicks(3527),
                            DateUpdated = new DateTime(2024, 6, 30, 0, 24, 27, 129, DateTimeKind.Local).AddTicks(3527),
                            DoB = new DateTime(1946, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Steven Spielberg",
                            Nationality = "American"
                        },
                        new
                        {
                            DirectorId = 2,
                            DateCreated = new DateTime(2024, 6, 30, 0, 24, 27, 129, DateTimeKind.Local).AddTicks(3529),
                            DateUpdated = new DateTime(2024, 6, 30, 0, 24, 27, 129, DateTimeKind.Local).AddTicks(3529),
                            DoB = new DateTime(1970, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Christopher Nolan",
                            Nationality = "British"
                        },
                        new
                        {
                            DirectorId = 3,
                            DateCreated = new DateTime(2024, 6, 30, 0, 24, 27, 129, DateTimeKind.Local).AddTicks(3530),
                            DateUpdated = new DateTime(2024, 6, 30, 0, 24, 27, 129, DateTimeKind.Local).AddTicks(3531),
                            DoB = new DateTime(1942, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Martin Scorsese",
                            Nationality = "American"
                        },
                        new
                        {
                            DirectorId = 4,
                            DateCreated = new DateTime(2024, 6, 30, 0, 24, 27, 129, DateTimeKind.Local).AddTicks(3531),
                            DateUpdated = new DateTime(2024, 6, 30, 0, 24, 27, 129, DateTimeKind.Local).AddTicks(3538),
                            DoB = new DateTime(1963, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Quentin Tarantino",
                            Nationality = "American"
                        },
                        new
                        {
                            DirectorId = 5,
                            DateCreated = new DateTime(2024, 6, 30, 0, 24, 27, 129, DateTimeKind.Local).AddTicks(3547),
                            DateUpdated = new DateTime(2024, 6, 30, 0, 24, 27, 129, DateTimeKind.Local).AddTicks(3547),
                            DoB = new DateTime(1954, 8, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "James Cameron",
                            Nationality = "Canadian"
                        },
                        new
                        {
                            DirectorId = 6,
                            DateCreated = new DateTime(2024, 6, 30, 0, 24, 27, 129, DateTimeKind.Local).AddTicks(3548),
                            DateUpdated = new DateTime(2024, 6, 30, 0, 24, 27, 129, DateTimeKind.Local).AddTicks(3548),
                            DoB = new DateTime(1951, 11, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Kathryn Bigelow",
                            Nationality = "American"
                        },
                        new
                        {
                            DirectorId = 7,
                            DateCreated = new DateTime(2024, 6, 30, 0, 24, 27, 129, DateTimeKind.Local).AddTicks(3549),
                            DateUpdated = new DateTime(2024, 6, 30, 0, 24, 27, 129, DateTimeKind.Local).AddTicks(3549),
                            DoB = new DateTime(1937, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ridley Scott",
                            Nationality = "British"
                        },
                        new
                        {
                            DirectorId = 8,
                            DateCreated = new DateTime(2024, 6, 30, 0, 24, 27, 129, DateTimeKind.Local).AddTicks(3550),
                            DateUpdated = new DateTime(2024, 6, 30, 0, 24, 27, 129, DateTimeKind.Local).AddTicks(3550),
                            DoB = new DateTime(1961, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Peter Jackson",
                            Nationality = "New Zealander"
                        },
                        new
                        {
                            DirectorId = 9,
                            DateCreated = new DateTime(2024, 6, 30, 0, 24, 27, 129, DateTimeKind.Local).AddTicks(3551),
                            DateUpdated = new DateTime(2024, 6, 30, 0, 24, 27, 129, DateTimeKind.Local).AddTicks(3551),
                            DoB = new DateTime(1964, 10, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Guillermo del Toro",
                            Nationality = "Mexican"
                        },
                        new
                        {
                            DirectorId = 10,
                            DateCreated = new DateTime(2024, 6, 30, 0, 24, 27, 129, DateTimeKind.Local).AddTicks(3552),
                            DateUpdated = new DateTime(2024, 6, 30, 0, 24, 27, 129, DateTimeKind.Local).AddTicks(3552),
                            DoB = new DateTime(1983, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Greta Gerwig",
                            Nationality = "American"
                        });
                });

            modelBuilder.Entity("Sever.Models.Genre", b =>
                {
                    b.Property<int>("GenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GenreId"), 1L, 1);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GenreId");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            GenreId = 1,
                            DateCreated = new DateTime(2024, 6, 30, 0, 24, 27, 129, DateTimeKind.Local).AddTicks(3572),
                            DateUpdated = new DateTime(2024, 6, 30, 0, 24, 27, 129, DateTimeKind.Local).AddTicks(3572),
                            Name = "Action"
                        },
                        new
                        {
                            GenreId = 2,
                            DateCreated = new DateTime(2024, 6, 30, 0, 24, 27, 129, DateTimeKind.Local).AddTicks(3573),
                            DateUpdated = new DateTime(2024, 6, 30, 0, 24, 27, 129, DateTimeKind.Local).AddTicks(3573),
                            Name = "Comedy"
                        },
                        new
                        {
                            GenreId = 3,
                            DateCreated = new DateTime(2024, 6, 30, 0, 24, 27, 129, DateTimeKind.Local).AddTicks(3574),
                            DateUpdated = new DateTime(2024, 6, 30, 0, 24, 27, 129, DateTimeKind.Local).AddTicks(3574),
                            Name = "Drama"
                        },
                        new
                        {
                            GenreId = 4,
                            DateCreated = new DateTime(2024, 6, 30, 0, 24, 27, 129, DateTimeKind.Local).AddTicks(3576),
                            DateUpdated = new DateTime(2024, 6, 30, 0, 24, 27, 129, DateTimeKind.Local).AddTicks(3576),
                            Name = "Horror"
                        },
                        new
                        {
                            GenreId = 5,
                            DateCreated = new DateTime(2024, 6, 30, 0, 24, 27, 129, DateTimeKind.Local).AddTicks(3577),
                            DateUpdated = new DateTime(2024, 6, 30, 0, 24, 27, 129, DateTimeKind.Local).AddTicks(3577),
                            Name = "Science-Fiction"
                        },
                        new
                        {
                            GenreId = 6,
                            DateCreated = new DateTime(2024, 6, 30, 0, 24, 27, 129, DateTimeKind.Local).AddTicks(3578),
                            DateUpdated = new DateTime(2024, 6, 30, 0, 24, 27, 129, DateTimeKind.Local).AddTicks(3578),
                            Name = "Romance"
                        },
                        new
                        {
                            GenreId = 7,
                            DateCreated = new DateTime(2024, 6, 30, 0, 24, 27, 129, DateTimeKind.Local).AddTicks(3579),
                            DateUpdated = new DateTime(2024, 6, 30, 0, 24, 27, 129, DateTimeKind.Local).AddTicks(3579),
                            Name = "Thriller"
                        },
                        new
                        {
                            GenreId = 8,
                            DateCreated = new DateTime(2024, 6, 30, 0, 24, 27, 129, DateTimeKind.Local).AddTicks(3580),
                            DateUpdated = new DateTime(2024, 6, 30, 0, 24, 27, 129, DateTimeKind.Local).AddTicks(3580),
                            Name = "Fantasy"
                        },
                        new
                        {
                            GenreId = 9,
                            DateCreated = new DateTime(2024, 6, 30, 0, 24, 27, 129, DateTimeKind.Local).AddTicks(3581),
                            DateUpdated = new DateTime(2024, 6, 30, 0, 24, 27, 129, DateTimeKind.Local).AddTicks(3581),
                            Name = "Animation"
                        },
                        new
                        {
                            GenreId = 10,
                            DateCreated = new DateTime(2024, 6, 30, 0, 24, 27, 129, DateTimeKind.Local).AddTicks(3581),
                            DateUpdated = new DateTime(2024, 6, 30, 0, 24, 27, 129, DateTimeKind.Local).AddTicks(3582),
                            Name = "Documentary"
                        });
                });

            modelBuilder.Entity("Sever.Models.Movie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovieId"), 1L, 1);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DirectorId")
                        .HasColumnType("int");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<string>("National")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfView")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MovieId");

                    b.HasIndex("DirectorId");

                    b.HasIndex("GenreId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            DateCreated = new DateTime(2024, 6, 30, 0, 24, 27, 129, DateTimeKind.Local).AddTicks(3595),
                            DateUpdated = new DateTime(2024, 6, 30, 0, 24, 27, 129, DateTimeKind.Local).AddTicks(3596),
                            Description = "Inception is a mind-bending thriller where dream invasion is possible. Dom Cobb, a skilled thief, extracts secrets from deep within the subconscious during dreams. Cobb is an international fugitive seeking redemption through one last job: to plant an idea instead of stealing it. Success could be the perfect crime.",
                            DirectorId = 2,
                            Duration = 148,
                            GenreId = 5,
                            National = "USA",
                            NumberOfView = 10,
                            ReleaseDate = new DateTime(2010, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Inception"
                        },
                        new
                        {
                            MovieId = 2,
                            DateCreated = new DateTime(2024, 6, 30, 0, 24, 27, 129, DateTimeKind.Local).AddTicks(3597),
                            DateUpdated = new DateTime(2024, 6, 30, 0, 24, 27, 129, DateTimeKind.Local).AddTicks(3598),
                            Description = "Titanic is a love story that unfolds on the ill-fated ship. Seventeen-year-old Rose boards with her aristocratic family, feeling suffocated by societal constraints and an impending arranged marriage. She meets Jack, a third-class passenger, and they fall in love amid the ship's grandeur and tragedy.",
                            DirectorId = 5,
                            Duration = 195,
                            GenreId = 6,
                            National = "USA",
                            NumberOfView = 8,
                            ReleaseDate = new DateTime(1997, 12, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Titanic"
                        },
                        new
                        {
                            MovieId = 3,
                            DateCreated = new DateTime(2024, 6, 30, 0, 24, 27, 129, DateTimeKind.Local).AddTicks(3599),
                            DateUpdated = new DateTime(2024, 6, 30, 0, 24, 27, 129, DateTimeKind.Local).AddTicks(3599),
                            Description = "Pulp Fiction intertwines the lives of Los Angeles criminals, including hitmen, a boxer, and a mob boss, in a series of interconnected stories blending violence and redemption.",
                            DirectorId = 4,
                            Duration = 154,
                            GenreId = 7,
                            National = "USA",
                            NumberOfView = 18,
                            ReleaseDate = new DateTime(1994, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Pulp Fiction"
                        },
                        new
                        {
                            MovieId = 4,
                            DateCreated = new DateTime(2024, 6, 30, 0, 24, 27, 129, DateTimeKind.Local).AddTicks(3600),
                            DateUpdated = new DateTime(2024, 6, 30, 0, 24, 27, 129, DateTimeKind.Local).AddTicks(3601),
                            Description = "The Dark Knight follows Batman as he confronts the Joker, a psychopathic criminal wreaking havoc on Gotham City. The conflict forces Batman to confront his own ideals and methods in combating crime.",
                            DirectorId = 2,
                            Duration = 152,
                            GenreId = 1,
                            National = "USA",
                            NumberOfView = 2,
                            ReleaseDate = new DateTime(2008, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Dark Knight"
                        },
                        new
                        {
                            MovieId = 5,
                            DateCreated = new DateTime(2024, 6, 30, 0, 24, 27, 129, DateTimeKind.Local).AddTicks(3602),
                            DateUpdated = new DateTime(2024, 6, 30, 0, 24, 27, 129, DateTimeKind.Local).AddTicks(3602),
                            Description = "Avatar follows Jake Sully, a paraplegic Marine, who becomes part of the Avatar Program on Pandora, where he integrates with the Na'vi to infiltrate the indigenous species for a corporate mission. However, his experiences lead him to question his allegiances and fight for Pandora's survival.",
                            DirectorId = 5,
                            Duration = 162,
                            GenreId = 5,
                            National = "USA",
                            NumberOfView = 10,
                            ReleaseDate = new DateTime(2009, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Avatar"
                        },
                        new
                        {
                            MovieId = 6,
                            DateCreated = new DateTime(2024, 6, 30, 0, 24, 27, 129, DateTimeKind.Local).AddTicks(3603),
                            DateUpdated = new DateTime(2024, 6, 30, 0, 24, 27, 129, DateTimeKind.Local).AddTicks(3603),
                            Description = "The Matrix centers on Neo, a computer hacker who discovers that reality is a simulated world created by sentient machines to subdue humanity. Neo joins a group of rebels to overthrow the machines and free humanity from their control.",
                            DirectorId = 7,
                            Duration = 136,
                            GenreId = 5,
                            National = "USA",
                            NumberOfView = 20,
                            ReleaseDate = new DateTime(1999, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Matrix"
                        },
                        new
                        {
                            MovieId = 7,
                            DateCreated = new DateTime(2024, 6, 30, 0, 24, 27, 129, DateTimeKind.Local).AddTicks(3604),
                            DateUpdated = new DateTime(2024, 6, 30, 0, 24, 27, 129, DateTimeKind.Local).AddTicks(3605),
                            Description = "La La Land tells the story of Mia, an aspiring actress, and Sebastian, a jazz musician, who meet and fall in love in Los Angeles while pursuing their dreams. Their relationship faces challenges as they navigate the competitive and demanding entertainment industry.",
                            DirectorId = 10,
                            Duration = 128,
                            GenreId = 6,
                            National = "USA",
                            NumberOfView = 7,
                            ReleaseDate = new DateTime(2016, 12, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "La La Land"
                        },
                        new
                        {
                            MovieId = 8,
                            DateCreated = new DateTime(2024, 6, 30, 0, 24, 27, 129, DateTimeKind.Local).AddTicks(3606),
                            DateUpdated = new DateTime(2024, 6, 30, 0, 24, 27, 129, DateTimeKind.Local).AddTicks(3606),
                            Description = "The Lord of the Rings: The Return of the King depicts the final battle for Middle-earth as Aragorn, Frodo, and their allies confront Sauron's forces in an epic conclusion to the trilogy.",
                            DirectorId = 8,
                            Duration = 201,
                            GenreId = 8,
                            National = "New Zealand",
                            NumberOfView = 80,
                            ReleaseDate = new DateTime(2003, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Lord of the Rings: The Return of the King"
                        },
                        new
                        {
                            MovieId = 9,
                            DateCreated = new DateTime(2024, 6, 30, 0, 24, 27, 129, DateTimeKind.Local).AddTicks(3607),
                            DateUpdated = new DateTime(2024, 6, 30, 0, 24, 27, 129, DateTimeKind.Local).AddTicks(3608),
                            Description = "Pan's Labyrinth follows Ofelia, a young girl in post-Civil War Spain, who discovers a mysterious labyrinth and encounters magical creatures. Amid her harsh reality, Ofelia navigates a world of fantasy to fulfill a daunting task.",
                            DirectorId = 9,
                            Duration = 118,
                            GenreId = 4,
                            National = "Mexico",
                            NumberOfView = 1,
                            ReleaseDate = new DateTime(2006, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Pan's Labyrinth"
                        },
                        new
                        {
                            MovieId = 10,
                            DateCreated = new DateTime(2024, 6, 30, 0, 24, 27, 129, DateTimeKind.Local).AddTicks(3608),
                            DateUpdated = new DateTime(2024, 6, 30, 0, 24, 27, 129, DateTimeKind.Local).AddTicks(3609),
                            Description = "Wonder Woman chronicles Diana, an Amazonian warrior princess, who leaves her home to fight alongside humans in World War I. As she discovers her powers and true destiny, she becomes a symbol of hope and inspiration.",
                            DirectorId = 9,
                            Duration = 141,
                            GenreId = 1,
                            National = "USA",
                            NumberOfView = 64,
                            ReleaseDate = new DateTime(2017, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Wonder Woman"
                        });
                });

            modelBuilder.Entity("Sever.Models.MovieActor", b =>
                {
                    b.Property<int>("MovieActorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovieActorId"), 1L, 1);

                    b.Property<int>("ActorId")
                        .HasColumnType("int");

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.HasKey("MovieActorId");

                    b.HasIndex("ActorId");

                    b.HasIndex("MovieId");

                    b.ToTable("MovieActors");
                });

            modelBuilder.Entity("Sever.Models.MovieMedia", b =>
                {
                    b.Property<int>("MovieMediaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovieMediaId"), 1L, 1);

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MovieMediaId");

                    b.HasIndex("MovieId");

                    b.ToTable("MoviesMedias");
                });

            modelBuilder.Entity("Sever.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            RoleId = 2,
                            Name = "Member"
                        },
                        new
                        {
                            RoleId = 5,
                            Name = "Guest"
                        });
                });

            modelBuilder.Entity("Sever.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"), 1L, 1);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            DateCreated = new DateTime(2024, 6, 30, 0, 24, 27, 129, DateTimeKind.Local).AddTicks(3265),
                            DateUpdated = new DateTime(2024, 6, 30, 0, 24, 27, 129, DateTimeKind.Local).AddTicks(3276),
                            Email = "admin@gmail.com",
                            FirstName = "Admin",
                            LastName = "First",
                            Password = "AQAAAAEAACcQAAAAEECsrYgr46/fnkWrUxraj5At9gzrCrWGUHqHHvo7FsC73wxOI9dRITXGZnIJ9mMX1A==",
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("Sever.Models.WatchList", b =>
                {
                    b.Property<int>("WatchListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WatchListId"), 1L, 1);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("WatchListId");

                    b.HasIndex("MovieId");

                    b.HasIndex("UserId");

                    b.ToTable("WatchLists");
                });

            modelBuilder.Entity("Sever.Models.Movie", b =>
                {
                    b.HasOne("Sever.Models.Director", "Director")
                        .WithMany("Movies")
                        .HasForeignKey("DirectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sever.Models.Genre", "Genre")
                        .WithMany("Movies")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Director");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("Sever.Models.MovieActor", b =>
                {
                    b.HasOne("Sever.Models.Actor", "Actor")
                        .WithMany("MovieActors")
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sever.Models.Movie", "Movie")
                        .WithMany("MovieActors")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("Sever.Models.MovieMedia", b =>
                {
                    b.HasOne("Sever.Models.Movie", "Movie")
                        .WithMany("MovieMedias")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("Sever.Models.User", b =>
                {
                    b.HasOne("Sever.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Sever.Models.WatchList", b =>
                {
                    b.HasOne("Sever.Models.Movie", "Movie")
                        .WithMany("WatchLists")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sever.Models.User", "User")
                        .WithMany("WatchLists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sever.Models.Actor", b =>
                {
                    b.Navigation("MovieActors");
                });

            modelBuilder.Entity("Sever.Models.Director", b =>
                {
                    b.Navigation("Movies");
                });

            modelBuilder.Entity("Sever.Models.Genre", b =>
                {
                    b.Navigation("Movies");
                });

            modelBuilder.Entity("Sever.Models.Movie", b =>
                {
                    b.Navigation("MovieActors");

                    b.Navigation("MovieMedias");

                    b.Navigation("WatchLists");
                });

            modelBuilder.Entity("Sever.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Sever.Models.User", b =>
                {
                    b.Navigation("WatchLists");
                });
#pragma warning restore 612, 618
        }
    }
}
