// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sever.Models;

#nullable disable

namespace Sever.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240807130708_change poster url")]
    partial class changeposterurl
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Sever.Models.Actor", b =>
                {
                    b.Property<int>("ActorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ActorId"), 1L, 1);

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DoB")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PublicId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ActorId");

                    b.ToTable("Actors");

                    b.HasData(
                        new
                        {
                            ActorId = 1,
                            AvatarUrl = "https://res.cloudinary.com/dl3zwdtki/image/upload/v1720286489/ACTOR/g4mdoefbqdrczrod7uwf.jpg",
                            DateCreated = new DateTime(2024, 8, 7, 20, 7, 6, 490, DateTimeKind.Local).AddTicks(1948),
                            DateUpdated = new DateTime(2024, 8, 7, 20, 7, 6, 490, DateTimeKind.Local).AddTicks(2037),
                            DoB = new DateTime(1965, 4, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Robert Downey Jr.",
                            Nationality = "American",
                            PublicId = "ACTOR/g4mdoefbqdrczrod7uwf"
                        },
                        new
                        {
                            ActorId = 2,
                            AvatarUrl = "https://res.cloudinary.com/dl3zwdtki/image/upload/v1720286489/ACTOR/g4mdoefbqdrczrod7uwf.jpg",
                            DateCreated = new DateTime(2024, 8, 7, 20, 7, 6, 490, DateTimeKind.Local).AddTicks(2130),
                            DateUpdated = new DateTime(2024, 8, 7, 20, 7, 6, 490, DateTimeKind.Local).AddTicks(2254),
                            DoB = new DateTime(1984, 11, 22, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Scarlett Johansson",
                            Nationality = "American",
                            PublicId = "ACTOR/g4mdoefbqdrczrod7uwf"
                        },
                        new
                        {
                            ActorId = 3,
                            AvatarUrl = "https://res.cloudinary.com/dl3zwdtki/image/upload/v1720286489/ACTOR/g4mdoefbqdrczrod7uwf.jpg",
                            DateCreated = new DateTime(2024, 8, 7, 20, 7, 6, 490, DateTimeKind.Local).AddTicks(3323),
                            DateUpdated = new DateTime(2024, 8, 7, 20, 7, 6, 490, DateTimeKind.Local).AddTicks(4281),
                            DoB = new DateTime(1974, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Leonardo DiCaprio",
                            Nationality = "American",
                            PublicId = "ACTOR/g4mdoefbqdrczrod7uwf"
                        },
                        new
                        {
                            ActorId = 4,
                            AvatarUrl = "https://res.cloudinary.com/dl3zwdtki/image/upload/v1720286489/ACTOR/g4mdoefbqdrczrod7uwf.jpg",
                            DateCreated = new DateTime(2024, 8, 7, 20, 7, 6, 490, DateTimeKind.Local).AddTicks(4373),
                            DateUpdated = new DateTime(2024, 8, 7, 20, 7, 6, 490, DateTimeKind.Local).AddTicks(4632),
                            DoB = new DateTime(1990, 8, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Jennifer Lawrence",
                            Nationality = "American",
                            PublicId = "ACTOR/g4mdoefbqdrczrod7uwf"
                        },
                        new
                        {
                            ActorId = 5,
                            AvatarUrl = "https://res.cloudinary.com/dl3zwdtki/image/upload/v1720286489/ACTOR/g4mdoefbqdrczrod7uwf.jpg",
                            DateCreated = new DateTime(2024, 8, 7, 20, 7, 6, 490, DateTimeKind.Local).AddTicks(4722),
                            DateUpdated = new DateTime(2024, 8, 7, 20, 7, 6, 490, DateTimeKind.Local).AddTicks(6917),
                            DoB = new DateTime(1954, 12, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Denzel Washington",
                            Nationality = "American",
                            PublicId = "ACTOR/g4mdoefbqdrczrod7uwf"
                        },
                        new
                        {
                            ActorId = 6,
                            AvatarUrl = "https://res.cloudinary.com/dl3zwdtki/image/upload/v1720286489/ACTOR/g4mdoefbqdrczrod7uwf.jpg",
                            DateCreated = new DateTime(2024, 8, 7, 20, 7, 6, 490, DateTimeKind.Local).AddTicks(7040),
                            DateUpdated = new DateTime(2024, 8, 7, 20, 7, 6, 490, DateTimeKind.Local).AddTicks(7128),
                            DoB = new DateTime(1981, 6, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Natalie Portman",
                            Nationality = "Israeli-American",
                            PublicId = "ACTOR/g4mdoefbqdrczrod7uwf"
                        },
                        new
                        {
                            ActorId = 7,
                            AvatarUrl = "https://res.cloudinary.com/dl3zwdtki/image/upload/v1720286489/ACTOR/g4mdoefbqdrczrod7uwf.jpg",
                            DateCreated = new DateTime(2024, 8, 7, 20, 7, 6, 490, DateTimeKind.Local).AddTicks(7216),
                            DateUpdated = new DateTime(2024, 8, 7, 20, 7, 6, 490, DateTimeKind.Local).AddTicks(7302),
                            DoB = new DateTime(1956, 7, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Tom Hanks",
                            Nationality = "American",
                            PublicId = "ACTOR/g4mdoefbqdrczrod7uwf"
                        },
                        new
                        {
                            ActorId = 8,
                            AvatarUrl = "https://res.cloudinary.com/dl3zwdtki/image/upload/v1720286489/ACTOR/g4mdoefbqdrczrod7uwf.jpg",
                            DateCreated = new DateTime(2024, 8, 7, 20, 7, 6, 490, DateTimeKind.Local).AddTicks(8353),
                            DateUpdated = new DateTime(2024, 8, 7, 20, 7, 6, 490, DateTimeKind.Local).AddTicks(8441),
                            DoB = new DateTime(1990, 4, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Emma Watson",
                            Nationality = "British",
                            PublicId = "ACTOR/g4mdoefbqdrczrod7uwf"
                        },
                        new
                        {
                            ActorId = 9,
                            AvatarUrl = "https://res.cloudinary.com/dl3zwdtki/image/upload/v1720286489/ACTOR/g4mdoefbqdrczrod7uwf.jpg",
                            DateCreated = new DateTime(2024, 8, 7, 20, 7, 6, 490, DateTimeKind.Local).AddTicks(9670),
                            DateUpdated = new DateTime(2024, 8, 7, 20, 7, 6, 491, DateTimeKind.Local).AddTicks(2909),
                            DoB = new DateTime(1963, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Brad Pitt",
                            Nationality = "American",
                            PublicId = "ACTOR/g4mdoefbqdrczrod7uwf"
                        },
                        new
                        {
                            ActorId = 10,
                            AvatarUrl = "https://res.cloudinary.com/dl3zwdtki/image/upload/v1720286489/ACTOR/g4mdoefbqdrczrod7uwf.jpg",
                            DateCreated = new DateTime(2024, 8, 7, 20, 7, 6, 491, DateTimeKind.Local).AddTicks(3055),
                            DateUpdated = new DateTime(2024, 8, 7, 20, 7, 6, 491, DateTimeKind.Local).AddTicks(3173),
                            DoB = new DateTime(1985, 4, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Gal Gadot",
                            Nationality = "Israeli",
                            PublicId = "ACTOR/g4mdoefbqdrczrod7uwf"
                        });
                });

            modelBuilder.Entity("Sever.Models.Director", b =>
                {
                    b.Property<int>("DirectorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DirectorId"), 1L, 1);

                    b.Property<string>("AvatarUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DoB")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PublicId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DirectorId");

                    b.ToTable("Directors");

                    b.HasData(
                        new
                        {
                            DirectorId = 1,
                            AvatarUrl = "https://res.cloudinary.com/dl3zwdtki/image/upload/v1720286507/DIRECTOR/os4brhm9sriu8nw09apr.webp",
                            DateCreated = new DateTime(2024, 8, 7, 20, 7, 6, 491, DateTimeKind.Local).AddTicks(6911),
                            DateUpdated = new DateTime(2024, 8, 7, 20, 7, 6, 491, DateTimeKind.Local).AddTicks(7045),
                            DoB = new DateTime(1946, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Steven Spielberg",
                            Nationality = "American",
                            PublicId = "DIRECTOR/os4brhm9sriu8nw09apr"
                        },
                        new
                        {
                            DirectorId = 2,
                            AvatarUrl = "https://res.cloudinary.com/dl3zwdtki/image/upload/v1720286507/DIRECTOR/os4brhm9sriu8nw09apr.webp",
                            DateCreated = new DateTime(2024, 8, 7, 20, 7, 6, 491, DateTimeKind.Local).AddTicks(7177),
                            DateUpdated = new DateTime(2024, 8, 7, 20, 7, 6, 491, DateTimeKind.Local).AddTicks(7291),
                            DoB = new DateTime(1970, 7, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Christopher Nolan",
                            Nationality = "British",
                            PublicId = "DIRECTOR/os4brhm9sriu8nw09apr"
                        },
                        new
                        {
                            DirectorId = 3,
                            AvatarUrl = "https://res.cloudinary.com/dl3zwdtki/image/upload/v1720286507/DIRECTOR/os4brhm9sriu8nw09apr.webp",
                            DateCreated = new DateTime(2024, 8, 7, 20, 7, 6, 491, DateTimeKind.Local).AddTicks(7404),
                            DateUpdated = new DateTime(2024, 8, 7, 20, 7, 6, 491, DateTimeKind.Local).AddTicks(7508),
                            DoB = new DateTime(1942, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Martin Scorsese",
                            Nationality = "American",
                            PublicId = "DIRECTOR/os4brhm9sriu8nw09apr"
                        },
                        new
                        {
                            DirectorId = 4,
                            AvatarUrl = "https://res.cloudinary.com/dl3zwdtki/image/upload/v1720286507/DIRECTOR/os4brhm9sriu8nw09apr.webp",
                            DateCreated = new DateTime(2024, 8, 7, 20, 7, 6, 491, DateTimeKind.Local).AddTicks(7633),
                            DateUpdated = new DateTime(2024, 8, 7, 20, 7, 6, 491, DateTimeKind.Local).AddTicks(7740),
                            DoB = new DateTime(1963, 3, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Quentin Tarantino",
                            Nationality = "American",
                            PublicId = "DIRECTOR/os4brhm9sriu8nw09apr"
                        },
                        new
                        {
                            DirectorId = 5,
                            AvatarUrl = "https://res.cloudinary.com/dl3zwdtki/image/upload/v1720286507/DIRECTOR/os4brhm9sriu8nw09apr.webp",
                            DateCreated = new DateTime(2024, 8, 7, 20, 7, 6, 491, DateTimeKind.Local).AddTicks(7849),
                            DateUpdated = new DateTime(2024, 8, 7, 20, 7, 6, 491, DateTimeKind.Local).AddTicks(7952),
                            DoB = new DateTime(1954, 8, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "James Cameron",
                            Nationality = "Canadian",
                            PublicId = "DIRECTOR/os4brhm9sriu8nw09apr"
                        },
                        new
                        {
                            DirectorId = 6,
                            AvatarUrl = "https://res.cloudinary.com/dl3zwdtki/image/upload/v1720286507/DIRECTOR/os4brhm9sriu8nw09apr.webp",
                            DateCreated = new DateTime(2024, 8, 7, 20, 7, 6, 491, DateTimeKind.Local).AddTicks(8061),
                            DateUpdated = new DateTime(2024, 8, 7, 20, 7, 6, 491, DateTimeKind.Local).AddTicks(8164),
                            DoB = new DateTime(1951, 11, 27, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Kathryn Bigelow",
                            Nationality = "American",
                            PublicId = "DIRECTOR/os4brhm9sriu8nw09apr"
                        },
                        new
                        {
                            DirectorId = 7,
                            AvatarUrl = "https://res.cloudinary.com/dl3zwdtki/image/upload/v1720286507/DIRECTOR/os4brhm9sriu8nw09apr.webp",
                            DateCreated = new DateTime(2024, 8, 7, 20, 7, 6, 491, DateTimeKind.Local).AddTicks(8286),
                            DateUpdated = new DateTime(2024, 8, 7, 20, 7, 6, 491, DateTimeKind.Local).AddTicks(8400),
                            DoB = new DateTime(1937, 11, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Ridley Scott",
                            Nationality = "British",
                            PublicId = "DIRECTOR/os4brhm9sriu8nw09apr"
                        },
                        new
                        {
                            DirectorId = 8,
                            AvatarUrl = "https://res.cloudinary.com/dl3zwdtki/image/upload/v1720286507/DIRECTOR/os4brhm9sriu8nw09apr.webp",
                            DateCreated = new DateTime(2024, 8, 7, 20, 7, 6, 491, DateTimeKind.Local).AddTicks(8512),
                            DateUpdated = new DateTime(2024, 8, 7, 20, 7, 6, 491, DateTimeKind.Local).AddTicks(8619),
                            DoB = new DateTime(1961, 10, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Peter Jackson",
                            Nationality = "New Zealander",
                            PublicId = "DIRECTOR/os4brhm9sriu8nw09apr"
                        },
                        new
                        {
                            DirectorId = 9,
                            AvatarUrl = "https://res.cloudinary.com/dl3zwdtki/image/upload/v1720286507/DIRECTOR/os4brhm9sriu8nw09apr.webp",
                            DateCreated = new DateTime(2024, 8, 7, 20, 7, 6, 491, DateTimeKind.Local).AddTicks(8729),
                            DateUpdated = new DateTime(2024, 8, 7, 20, 7, 6, 491, DateTimeKind.Local).AddTicks(8838),
                            DoB = new DateTime(1964, 10, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Guillermo del Toro",
                            Nationality = "Mexican",
                            PublicId = "DIRECTOR/os4brhm9sriu8nw09apr"
                        },
                        new
                        {
                            DirectorId = 10,
                            AvatarUrl = "https://res.cloudinary.com/dl3zwdtki/image/upload/v1720286507/DIRECTOR/os4brhm9sriu8nw09apr.webp",
                            DateCreated = new DateTime(2024, 8, 7, 20, 7, 6, 491, DateTimeKind.Local).AddTicks(8953),
                            DateUpdated = new DateTime(2024, 8, 7, 20, 7, 6, 491, DateTimeKind.Local).AddTicks(9057),
                            DoB = new DateTime(1983, 8, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Name = "Greta Gerwig",
                            Nationality = "American",
                            PublicId = "DIRECTOR/os4brhm9sriu8nw09apr"
                        });
                });

            modelBuilder.Entity("Sever.Models.Genre", b =>
                {
                    b.Property<int>("GenreId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GenreId"), 1L, 1);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("GenreId");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            GenreId = 1,
                            DateCreated = new DateTime(2024, 8, 7, 20, 7, 6, 492, DateTimeKind.Local).AddTicks(1558),
                            DateUpdated = new DateTime(2024, 8, 7, 20, 7, 6, 492, DateTimeKind.Local).AddTicks(1694),
                            Name = "Action"
                        },
                        new
                        {
                            GenreId = 2,
                            DateCreated = new DateTime(2024, 8, 7, 20, 7, 6, 492, DateTimeKind.Local).AddTicks(1828),
                            DateUpdated = new DateTime(2024, 8, 7, 20, 7, 6, 492, DateTimeKind.Local).AddTicks(1958),
                            Name = "Comedy"
                        },
                        new
                        {
                            GenreId = 3,
                            DateCreated = new DateTime(2024, 8, 7, 20, 7, 6, 492, DateTimeKind.Local).AddTicks(2091),
                            DateUpdated = new DateTime(2024, 8, 7, 20, 7, 6, 492, DateTimeKind.Local).AddTicks(2217),
                            Name = "Drama"
                        },
                        new
                        {
                            GenreId = 4,
                            DateCreated = new DateTime(2024, 8, 7, 20, 7, 6, 492, DateTimeKind.Local).AddTicks(2350),
                            DateUpdated = new DateTime(2024, 8, 7, 20, 7, 6, 492, DateTimeKind.Local).AddTicks(2477),
                            Name = "Horror"
                        },
                        new
                        {
                            GenreId = 5,
                            DateCreated = new DateTime(2024, 8, 7, 20, 7, 6, 492, DateTimeKind.Local).AddTicks(2607),
                            DateUpdated = new DateTime(2024, 8, 7, 20, 7, 6, 492, DateTimeKind.Local).AddTicks(2733),
                            Name = "Science-Fiction"
                        },
                        new
                        {
                            GenreId = 6,
                            DateCreated = new DateTime(2024, 8, 7, 20, 7, 6, 492, DateTimeKind.Local).AddTicks(2864),
                            DateUpdated = new DateTime(2024, 8, 7, 20, 7, 6, 492, DateTimeKind.Local).AddTicks(2993),
                            Name = "Romance"
                        },
                        new
                        {
                            GenreId = 7,
                            DateCreated = new DateTime(2024, 8, 7, 20, 7, 6, 492, DateTimeKind.Local).AddTicks(3122),
                            DateUpdated = new DateTime(2024, 8, 7, 20, 7, 6, 492, DateTimeKind.Local).AddTicks(3251),
                            Name = "Thriller"
                        },
                        new
                        {
                            GenreId = 8,
                            DateCreated = new DateTime(2024, 8, 7, 20, 7, 6, 492, DateTimeKind.Local).AddTicks(3381),
                            DateUpdated = new DateTime(2024, 8, 7, 20, 7, 6, 492, DateTimeKind.Local).AddTicks(3507),
                            Name = "Fantasy"
                        },
                        new
                        {
                            GenreId = 9,
                            DateCreated = new DateTime(2024, 8, 7, 20, 7, 6, 492, DateTimeKind.Local).AddTicks(3637),
                            DateUpdated = new DateTime(2024, 8, 7, 20, 7, 6, 492, DateTimeKind.Local).AddTicks(3766),
                            Name = "Animation"
                        },
                        new
                        {
                            GenreId = 10,
                            DateCreated = new DateTime(2024, 8, 7, 20, 7, 6, 492, DateTimeKind.Local).AddTicks(3897),
                            DateUpdated = new DateTime(2024, 8, 7, 20, 7, 6, 492, DateTimeKind.Local).AddTicks(4023),
                            Name = "Documentary"
                        });
                });

            modelBuilder.Entity("Sever.Models.Movie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovieId"), 1L, 1);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DirectorId")
                        .HasColumnType("int");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<string>("National")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("NumberOfView")
                        .HasColumnType("int");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MovieId");

                    b.HasIndex("DirectorId");

                    b.HasIndex("GenreId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            DateCreated = new DateTime(2024, 8, 7, 20, 7, 6, 492, DateTimeKind.Local).AddTicks(4278),
                            DateUpdated = new DateTime(2024, 8, 7, 20, 7, 6, 492, DateTimeKind.Local).AddTicks(4409),
                            Description = "Inception is a mind-bending thriller where dream invasion is possible. Dom Cobb, a skilled thief, extracts secrets from deep within the subconscious during dreams. Cobb is an international fugitive seeking redemption through one last job: to plant an idea instead of stealing it. Success could be the perfect crime.",
                            DirectorId = 2,
                            Duration = 148,
                            GenreId = 5,
                            National = "USA",
                            NumberOfView = 10,
                            ReleaseDate = new DateTime(2010, 7, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Inception"
                        },
                        new
                        {
                            MovieId = 2,
                            DateCreated = new DateTime(2024, 8, 7, 20, 7, 6, 492, DateTimeKind.Local).AddTicks(4546),
                            DateUpdated = new DateTime(2024, 8, 7, 20, 7, 6, 492, DateTimeKind.Local).AddTicks(4676),
                            Description = "Titanic is a love story that unfolds on the ill-fated ship. Seventeen-year-old Rose boards with her aristocratic family, feeling suffocated by societal constraints and an impending arranged marriage. She meets Jack, a third-class passenger, and they fall in love amid the ship's grandeur and tragedy.",
                            DirectorId = 5,
                            Duration = 195,
                            GenreId = 6,
                            National = "USA",
                            NumberOfView = 8,
                            ReleaseDate = new DateTime(1997, 12, 19, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Titanic"
                        },
                        new
                        {
                            MovieId = 3,
                            DateCreated = new DateTime(2024, 8, 7, 20, 7, 6, 492, DateTimeKind.Local).AddTicks(4815),
                            DateUpdated = new DateTime(2024, 8, 7, 20, 7, 6, 492, DateTimeKind.Local).AddTicks(4943),
                            Description = "Pulp Fiction intertwines the lives of Los Angeles criminals, including hitmen, a boxer, and a mob boss, in a series of interconnected stories blending violence and redemption.",
                            DirectorId = 4,
                            Duration = 154,
                            GenreId = 7,
                            National = "USA",
                            NumberOfView = 18,
                            ReleaseDate = new DateTime(1994, 10, 14, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Pulp Fiction"
                        },
                        new
                        {
                            MovieId = 4,
                            DateCreated = new DateTime(2024, 8, 7, 20, 7, 6, 492, DateTimeKind.Local).AddTicks(5196),
                            DateUpdated = new DateTime(2024, 8, 7, 20, 7, 6, 492, DateTimeKind.Local).AddTicks(5324),
                            Description = "The Dark Knight follows Batman as he confronts the Joker, a psychopathic criminal wreaking havoc on Gotham City. The conflict forces Batman to confront his own ideals and methods in combating crime.",
                            DirectorId = 2,
                            Duration = 152,
                            GenreId = 1,
                            National = "USA",
                            NumberOfView = 2,
                            ReleaseDate = new DateTime(2008, 7, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Dark Knight"
                        },
                        new
                        {
                            MovieId = 5,
                            DateCreated = new DateTime(2024, 8, 7, 20, 7, 6, 492, DateTimeKind.Local).AddTicks(6713),
                            DateUpdated = new DateTime(2024, 8, 7, 20, 7, 6, 492, DateTimeKind.Local).AddTicks(6841),
                            Description = "Avatar follows Jake Sully, a paraplegic Marine, who becomes part of the Avatar Program on Pandora, where he integrates with the Na'vi to infiltrate the indigenous species for a corporate mission. However, his experiences lead him to question his allegiances and fight for Pandora's survival.",
                            DirectorId = 5,
                            Duration = 162,
                            GenreId = 5,
                            National = "USA",
                            NumberOfView = 10,
                            ReleaseDate = new DateTime(2009, 12, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Avatar"
                        },
                        new
                        {
                            MovieId = 6,
                            DateCreated = new DateTime(2024, 8, 7, 20, 7, 6, 492, DateTimeKind.Local).AddTicks(6974),
                            DateUpdated = new DateTime(2024, 8, 7, 20, 7, 6, 492, DateTimeKind.Local).AddTicks(7102),
                            Description = "The Matrix centers on Neo, a computer hacker who discovers that reality is a simulated world created by sentient machines to subdue humanity. Neo joins a group of rebels to overthrow the machines and free humanity from their control.",
                            DirectorId = 7,
                            Duration = 136,
                            GenreId = 5,
                            National = "USA",
                            NumberOfView = 20,
                            ReleaseDate = new DateTime(1999, 3, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Matrix"
                        },
                        new
                        {
                            MovieId = 7,
                            DateCreated = new DateTime(2024, 8, 7, 20, 7, 6, 492, DateTimeKind.Local).AddTicks(7236),
                            DateUpdated = new DateTime(2024, 8, 7, 20, 7, 6, 492, DateTimeKind.Local).AddTicks(7362),
                            Description = "La La Land tells the story of Mia, an aspiring actress, and Sebastian, a jazz musician, who meet and fall in love in Los Angeles while pursuing their dreams. Their relationship faces challenges as they navigate the competitive and demanding entertainment industry.",
                            DirectorId = 10,
                            Duration = 128,
                            GenreId = 6,
                            National = "USA",
                            NumberOfView = 7,
                            ReleaseDate = new DateTime(2016, 12, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "La La Land"
                        },
                        new
                        {
                            MovieId = 8,
                            DateCreated = new DateTime(2024, 8, 7, 20, 7, 6, 492, DateTimeKind.Local).AddTicks(7497),
                            DateUpdated = new DateTime(2024, 8, 7, 20, 7, 6, 492, DateTimeKind.Local).AddTicks(7625),
                            Description = "The Lord of the Rings: The Return of the King depicts the final battle for Middle-earth as Aragorn, Frodo, and their allies confront Sauron's forces in an epic conclusion to the trilogy.",
                            DirectorId = 8,
                            Duration = 201,
                            GenreId = 8,
                            National = "New Zealand",
                            NumberOfView = 80,
                            ReleaseDate = new DateTime(2003, 12, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "The Lord of the Rings: The Return of the King"
                        },
                        new
                        {
                            MovieId = 9,
                            DateCreated = new DateTime(2024, 8, 7, 20, 7, 6, 492, DateTimeKind.Local).AddTicks(7757),
                            DateUpdated = new DateTime(2024, 8, 7, 20, 7, 6, 492, DateTimeKind.Local).AddTicks(7884),
                            Description = "Pan's Labyrinth follows Ofelia, a young girl in post-Civil War Spain, who discovers a mysterious labyrinth and encounters magical creatures. Amid her harsh reality, Ofelia navigates a world of fantasy to fulfill a daunting task.",
                            DirectorId = 9,
                            Duration = 118,
                            GenreId = 4,
                            National = "Mexico",
                            NumberOfView = 1,
                            ReleaseDate = new DateTime(2006, 10, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Pan's Labyrinth"
                        },
                        new
                        {
                            MovieId = 10,
                            DateCreated = new DateTime(2024, 8, 7, 20, 7, 6, 492, DateTimeKind.Local).AddTicks(8018),
                            DateUpdated = new DateTime(2024, 8, 7, 20, 7, 6, 492, DateTimeKind.Local).AddTicks(8144),
                            Description = "Wonder Woman chronicles Diana, an Amazonian warrior princess, who leaves her home to fight alongside humans in World War I. As she discovers her powers and true destiny, she becomes a symbol of hope and inspiration.",
                            DirectorId = 9,
                            Duration = 141,
                            GenreId = 1,
                            National = "USA",
                            NumberOfView = 64,
                            ReleaseDate = new DateTime(2017, 6, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Wonder Woman"
                        });
                });

            modelBuilder.Entity("Sever.Models.MovieActor", b =>
                {
                    b.Property<int>("MovieActorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovieActorId"), 1L, 1);

                    b.Property<int>("ActorId")
                        .HasColumnType("int");

                    b.Property<string>("CharacterName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.HasKey("MovieActorId");

                    b.HasIndex("ActorId");

                    b.HasIndex("MovieId");

                    b.ToTable("MovieActors");

                    b.HasData(
                        new
                        {
                            MovieActorId = 1,
                            ActorId = 1,
                            CharacterName = "Cobb",
                            DateCreated = new DateTime(2024, 8, 7, 20, 7, 6, 492, DateTimeKind.Local).AddTicks(8390),
                            DateUpdated = new DateTime(2024, 8, 7, 20, 7, 6, 492, DateTimeKind.Local).AddTicks(8521),
                            MovieId = 1
                        },
                        new
                        {
                            MovieActorId = 2,
                            ActorId = 2,
                            CharacterName = "Ariadne",
                            DateCreated = new DateTime(2024, 8, 7, 20, 7, 6, 492, DateTimeKind.Local).AddTicks(8659),
                            DateUpdated = new DateTime(2024, 8, 7, 20, 7, 6, 492, DateTimeKind.Local).AddTicks(8786),
                            MovieId = 1
                        },
                        new
                        {
                            MovieActorId = 3,
                            ActorId = 3,
                            CharacterName = "Arthur",
                            DateCreated = new DateTime(2024, 8, 7, 20, 7, 6, 492, DateTimeKind.Local).AddTicks(8918),
                            DateUpdated = new DateTime(2024, 8, 7, 20, 7, 6, 492, DateTimeKind.Local).AddTicks(9049),
                            MovieId = 1
                        },
                        new
                        {
                            MovieActorId = 4,
                            ActorId = 3,
                            CharacterName = "Jack Dawson",
                            DateCreated = new DateTime(2024, 8, 7, 20, 7, 6, 492, DateTimeKind.Local).AddTicks(9180),
                            DateUpdated = new DateTime(2024, 8, 7, 20, 7, 6, 492, DateTimeKind.Local).AddTicks(9308),
                            MovieId = 2
                        },
                        new
                        {
                            MovieActorId = 5,
                            ActorId = 4,
                            CharacterName = "Rose DeWitt Bukater",
                            DateCreated = new DateTime(2024, 8, 7, 20, 7, 6, 492, DateTimeKind.Local).AddTicks(9439),
                            DateUpdated = new DateTime(2024, 8, 7, 20, 7, 6, 492, DateTimeKind.Local).AddTicks(9564),
                            MovieId = 2
                        },
                        new
                        {
                            MovieActorId = 6,
                            ActorId = 5,
                            CharacterName = "Cal Hockley",
                            DateCreated = new DateTime(2024, 8, 7, 20, 7, 6, 492, DateTimeKind.Local).AddTicks(9697),
                            DateUpdated = new DateTime(2024, 8, 7, 20, 7, 6, 492, DateTimeKind.Local).AddTicks(9821),
                            MovieId = 2
                        },
                        new
                        {
                            MovieActorId = 7,
                            ActorId = 5,
                            CharacterName = "Vincent Vega",
                            DateCreated = new DateTime(2024, 8, 7, 20, 7, 6, 492, DateTimeKind.Local).AddTicks(9953),
                            DateUpdated = new DateTime(2024, 8, 7, 20, 7, 6, 493, DateTimeKind.Local).AddTicks(75),
                            MovieId = 3
                        },
                        new
                        {
                            MovieActorId = 8,
                            ActorId = 6,
                            CharacterName = "Mia Wallace",
                            DateCreated = new DateTime(2024, 8, 7, 20, 7, 6, 493, DateTimeKind.Local).AddTicks(205),
                            DateUpdated = new DateTime(2024, 8, 7, 20, 7, 6, 493, DateTimeKind.Local).AddTicks(334),
                            MovieId = 3
                        },
                        new
                        {
                            MovieActorId = 9,
                            ActorId = 7,
                            CharacterName = "Jules Winnfield",
                            DateCreated = new DateTime(2024, 8, 7, 20, 7, 6, 493, DateTimeKind.Local).AddTicks(464),
                            DateUpdated = new DateTime(2024, 8, 7, 20, 7, 6, 493, DateTimeKind.Local).AddTicks(588),
                            MovieId = 3
                        },
                        new
                        {
                            MovieActorId = 10,
                            ActorId = 1,
                            CharacterName = "Bruce Wayne/Batman",
                            DateCreated = new DateTime(2024, 8, 7, 20, 7, 6, 493, DateTimeKind.Local).AddTicks(721),
                            DateUpdated = new DateTime(2024, 8, 7, 20, 7, 6, 493, DateTimeKind.Local).AddTicks(850),
                            MovieId = 4
                        },
                        new
                        {
                            MovieActorId = 11,
                            ActorId = 8,
                            CharacterName = "Joker",
                            DateCreated = new DateTime(2024, 8, 7, 20, 7, 6, 493, DateTimeKind.Local).AddTicks(980),
                            DateUpdated = new DateTime(2024, 8, 7, 20, 7, 6, 493, DateTimeKind.Local).AddTicks(1106),
                            MovieId = 4
                        },
                        new
                        {
                            MovieActorId = 12,
                            ActorId = 9,
                            CharacterName = "Harvey Dent",
                            DateCreated = new DateTime(2024, 8, 7, 20, 7, 6, 493, DateTimeKind.Local).AddTicks(1236),
                            DateUpdated = new DateTime(2024, 8, 7, 20, 7, 6, 493, DateTimeKind.Local).AddTicks(1362),
                            MovieId = 4
                        },
                        new
                        {
                            MovieActorId = 13,
                            ActorId = 2,
                            CharacterName = "Jake Sully",
                            DateCreated = new DateTime(2024, 8, 7, 20, 7, 6, 493, DateTimeKind.Local).AddTicks(1492),
                            DateUpdated = new DateTime(2024, 8, 7, 20, 7, 6, 493, DateTimeKind.Local).AddTicks(1616),
                            MovieId = 5
                        },
                        new
                        {
                            MovieActorId = 14,
                            ActorId = 10,
                            CharacterName = "Neytiri",
                            DateCreated = new DateTime(2024, 8, 7, 20, 7, 6, 493, DateTimeKind.Local).AddTicks(1749),
                            DateUpdated = new DateTime(2024, 8, 7, 20, 7, 6, 493, DateTimeKind.Local).AddTicks(1872),
                            MovieId = 5
                        },
                        new
                        {
                            MovieActorId = 15,
                            ActorId = 3,
                            CharacterName = "Colonel Miles Quaritch",
                            DateCreated = new DateTime(2024, 8, 7, 20, 7, 6, 493, DateTimeKind.Local).AddTicks(2001),
                            DateUpdated = new DateTime(2024, 8, 7, 20, 7, 6, 493, DateTimeKind.Local).AddTicks(2128),
                            MovieId = 5
                        },
                        new
                        {
                            MovieActorId = 16,
                            ActorId = 1,
                            CharacterName = "Neo",
                            DateCreated = new DateTime(2024, 8, 7, 20, 7, 6, 493, DateTimeKind.Local).AddTicks(2258),
                            DateUpdated = new DateTime(2024, 8, 7, 20, 7, 6, 493, DateTimeKind.Local).AddTicks(2383),
                            MovieId = 6
                        },
                        new
                        {
                            MovieActorId = 17,
                            ActorId = 5,
                            CharacterName = "Morpheus",
                            DateCreated = new DateTime(2024, 8, 7, 20, 7, 6, 493, DateTimeKind.Local).AddTicks(2511),
                            DateUpdated = new DateTime(2024, 8, 7, 20, 7, 6, 493, DateTimeKind.Local).AddTicks(2637),
                            MovieId = 6
                        },
                        new
                        {
                            MovieActorId = 18,
                            ActorId = 7,
                            CharacterName = "Trinity",
                            DateCreated = new DateTime(2024, 8, 7, 20, 7, 6, 493, DateTimeKind.Local).AddTicks(2767),
                            DateUpdated = new DateTime(2024, 8, 7, 20, 7, 6, 493, DateTimeKind.Local).AddTicks(2892),
                            MovieId = 6
                        },
                        new
                        {
                            MovieActorId = 19,
                            ActorId = 6,
                            CharacterName = "Sebastian",
                            DateCreated = new DateTime(2024, 8, 7, 20, 7, 6, 493, DateTimeKind.Local).AddTicks(3024),
                            DateUpdated = new DateTime(2024, 8, 7, 20, 7, 6, 493, DateTimeKind.Local).AddTicks(3150),
                            MovieId = 7
                        },
                        new
                        {
                            MovieActorId = 20,
                            ActorId = 7,
                            CharacterName = "Mia",
                            DateCreated = new DateTime(2024, 8, 7, 20, 7, 6, 493, DateTimeKind.Local).AddTicks(3280),
                            DateUpdated = new DateTime(2024, 8, 7, 20, 7, 6, 493, DateTimeKind.Local).AddTicks(4340),
                            MovieId = 7
                        },
                        new
                        {
                            MovieActorId = 21,
                            ActorId = 8,
                            CharacterName = "Keith",
                            DateCreated = new DateTime(2024, 8, 7, 20, 7, 6, 493, DateTimeKind.Local).AddTicks(4446),
                            DateUpdated = new DateTime(2024, 8, 7, 20, 7, 6, 493, DateTimeKind.Local).AddTicks(4530),
                            MovieId = 7
                        },
                        new
                        {
                            MovieActorId = 22,
                            ActorId = 8,
                            CharacterName = "Frodo Baggins",
                            DateCreated = new DateTime(2024, 8, 7, 20, 7, 6, 493, DateTimeKind.Local).AddTicks(4618),
                            DateUpdated = new DateTime(2024, 8, 7, 20, 7, 6, 493, DateTimeKind.Local).AddTicks(4700),
                            MovieId = 8
                        },
                        new
                        {
                            MovieActorId = 23,
                            ActorId = 9,
                            CharacterName = "Aragorn",
                            DateCreated = new DateTime(2024, 8, 7, 20, 7, 6, 493, DateTimeKind.Local).AddTicks(4785),
                            DateUpdated = new DateTime(2024, 8, 7, 20, 7, 6, 493, DateTimeKind.Local).AddTicks(4868),
                            MovieId = 8
                        },
                        new
                        {
                            MovieActorId = 24,
                            ActorId = 10,
                            CharacterName = "Gandalf",
                            DateCreated = new DateTime(2024, 8, 7, 20, 7, 6, 493, DateTimeKind.Local).AddTicks(4953),
                            DateUpdated = new DateTime(2024, 8, 7, 20, 7, 6, 493, DateTimeKind.Local).AddTicks(5035),
                            MovieId = 8
                        },
                        new
                        {
                            MovieActorId = 25,
                            ActorId = 10,
                            CharacterName = "Ofelia",
                            DateCreated = new DateTime(2024, 8, 7, 20, 7, 6, 493, DateTimeKind.Local).AddTicks(5121),
                            DateUpdated = new DateTime(2024, 8, 7, 20, 7, 6, 493, DateTimeKind.Local).AddTicks(5202),
                            MovieId = 9
                        },
                        new
                        {
                            MovieActorId = 26,
                            ActorId = 6,
                            CharacterName = "Carmen",
                            DateCreated = new DateTime(2024, 8, 7, 20, 7, 6, 493, DateTimeKind.Local).AddTicks(5287),
                            DateUpdated = new DateTime(2024, 8, 7, 20, 7, 6, 493, DateTimeKind.Local).AddTicks(5368),
                            MovieId = 9
                        },
                        new
                        {
                            MovieActorId = 27,
                            ActorId = 7,
                            CharacterName = "Captain Vidal",
                            DateCreated = new DateTime(2024, 8, 7, 20, 7, 6, 493, DateTimeKind.Local).AddTicks(5452),
                            DateUpdated = new DateTime(2024, 8, 7, 20, 7, 6, 493, DateTimeKind.Local).AddTicks(5535),
                            MovieId = 9
                        },
                        new
                        {
                            MovieActorId = 28,
                            ActorId = 2,
                            CharacterName = "Diana Prince/Wonder Woman",
                            DateCreated = new DateTime(2024, 8, 7, 20, 7, 6, 493, DateTimeKind.Local).AddTicks(5620),
                            DateUpdated = new DateTime(2024, 8, 7, 20, 7, 6, 493, DateTimeKind.Local).AddTicks(5702),
                            MovieId = 10
                        },
                        new
                        {
                            MovieActorId = 29,
                            ActorId = 4,
                            CharacterName = "Steve Trevor",
                            DateCreated = new DateTime(2024, 8, 7, 20, 7, 6, 493, DateTimeKind.Local).AddTicks(5787),
                            DateUpdated = new DateTime(2024, 8, 7, 20, 7, 6, 493, DateTimeKind.Local).AddTicks(5870),
                            MovieId = 10
                        },
                        new
                        {
                            MovieActorId = 30,
                            ActorId = 3,
                            CharacterName = "Antiope",
                            DateCreated = new DateTime(2024, 8, 7, 20, 7, 6, 493, DateTimeKind.Local).AddTicks(5954),
                            DateUpdated = new DateTime(2024, 8, 7, 20, 7, 6, 493, DateTimeKind.Local).AddTicks(6036),
                            MovieId = 10
                        });
                });

            modelBuilder.Entity("Sever.Models.MovieMedia", b =>
                {
                    b.Property<int>("MovieMediaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MovieMediaId"), 1L, 1);

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PublicId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MovieMediaId");

                    b.HasIndex("MovieId");

                    b.ToTable("MoviesMedias");

                    b.HasData(
                        new
                        {
                            MovieMediaId = 1,
                            MovieId = 1,
                            Name = "Inception Poster",
                            PublicId = "POSTER/xhprcuwrw5rewdojm9ke",
                            Type = 2,
                            Url = "https://res.cloudinary.com/dl3zwdtki/image/upload/v1722168426/POSTER/p6ixrrzrgzoywdhmbarj.jpg"
                        },
                        new
                        {
                            MovieMediaId = 2,
                            MovieId = 1,
                            Name = "Inception Banner",
                            PublicId = "BANNER/g5dqzcs4zwgxvvw3lsma",
                            Type = 3,
                            Url = "https://res.cloudinary.com/dl3zwdtki/image/upload/v1719774957/BANNER/g5dqzcs4zwgxvvw3lsma.jpg"
                        },
                        new
                        {
                            MovieMediaId = 3,
                            MovieId = 1,
                            Name = "Inception Trailer",
                            PublicId = "TRAILER/kou9a1hm4axazrmvxfgh",
                            Type = 4,
                            Url = "https://res.cloudinary.com/dl3zwdtki/video/upload/v1719775117/TRAILER/kou9a1hm4axazrmvxfgh.mp4"
                        },
                        new
                        {
                            MovieMediaId = 4,
                            MovieId = 1,
                            Name = "Inception Video",
                            PublicId = "VIDEO/fnoqi8bubpp3zk2l44y5",
                            Type = 6,
                            Url = "https://res.cloudinary.com/dl3zwdtki/video/upload/v1719775341/VIDEO/fnoqi8bubpp3zk2l44y5.mp4"
                        },
                        new
                        {
                            MovieMediaId = 5,
                            MovieId = 2,
                            Name = "Titanic Poster",
                            PublicId = "POSTER/xhprcuwrw5rewdojm9ke",
                            Type = 2,
                            Url = "https://res.cloudinary.com/dl3zwdtki/image/upload/v1722168426/POSTER/p6ixrrzrgzoywdhmbarj.jpg"
                        },
                        new
                        {
                            MovieMediaId = 6,
                            MovieId = 2,
                            Name = "Titanic Banner",
                            PublicId = "BANNER/g5dqzcs4zwgxvvw3lsma",
                            Type = 3,
                            Url = "https://res.cloudinary.com/dl3zwdtki/image/upload/v1719774957/BANNER/g5dqzcs4zwgxvvw3lsma.jpg"
                        },
                        new
                        {
                            MovieMediaId = 7,
                            MovieId = 2,
                            Name = "Titanic Trailer",
                            PublicId = "TRAILER/kou9a1hm4axazrmvxfgh",
                            Type = 4,
                            Url = "https://res.cloudinary.com/dl3zwdtki/video/upload/v1719775117/TRAILER/kou9a1hm4axazrmvxfgh.mp4"
                        },
                        new
                        {
                            MovieMediaId = 8,
                            MovieId = 2,
                            Name = "Titanic Video",
                            PublicId = "VIDEO/fnoqi8bubpp3zk2l44y5",
                            Type = 6,
                            Url = "https://res.cloudinary.com/dl3zwdtki/video/upload/v1719775341/VIDEO/fnoqi8bubpp3zk2l44y5.mp4"
                        },
                        new
                        {
                            MovieMediaId = 9,
                            MovieId = 3,
                            Name = "Pulp Fiction Poster",
                            PublicId = "POSTER/xhprcuwrw5rewdojm9ke",
                            Type = 2,
                            Url = "https://res.cloudinary.com/dl3zwdtki/image/upload/v1722168426/POSTER/p6ixrrzrgzoywdhmbarj.jpg"
                        },
                        new
                        {
                            MovieMediaId = 10,
                            MovieId = 3,
                            Name = "Pulp Fiction Banner",
                            PublicId = "BANNER/g5dqzcs4zwgxvvw3lsma",
                            Type = 3,
                            Url = "https://res.cloudinary.com/dl3zwdtki/image/upload/v1719774957/BANNER/g5dqzcs4zwgxvvw3lsma.jpg"
                        },
                        new
                        {
                            MovieMediaId = 11,
                            MovieId = 3,
                            Name = "Pulp Fiction Trailer",
                            PublicId = "TRAILER/kou9a1hm4axazrmvxfgh",
                            Type = 4,
                            Url = "https://res.cloudinary.com/dl3zwdtki/video/upload/v1719775117/TRAILER/kou9a1hm4axazrmvxfgh.mp4"
                        },
                        new
                        {
                            MovieMediaId = 12,
                            MovieId = 3,
                            Name = "Pulp Fiction Video",
                            PublicId = "VIDEO/fnoqi8bubpp3zk2l44y5",
                            Type = 6,
                            Url = "https://res.cloudinary.com/dl3zwdtki/video/upload/v1719775341/VIDEO/fnoqi8bubpp3zk2l44y5.mp4"
                        },
                        new
                        {
                            MovieMediaId = 13,
                            MovieId = 4,
                            Name = "The Dark Knight Poster",
                            PublicId = "POSTER/xhprcuwrw5rewdojm9ke",
                            Type = 2,
                            Url = "https://res.cloudinary.com/dl3zwdtki/image/upload/v1722168426/POSTER/p6ixrrzrgzoywdhmbarj.jpg"
                        },
                        new
                        {
                            MovieMediaId = 14,
                            MovieId = 4,
                            Name = "The Dark Knight Banner",
                            PublicId = "BANNER/g5dqzcs4zwgxvvw3lsma",
                            Type = 3,
                            Url = "https://res.cloudinary.com/dl3zwdtki/image/upload/v1719774957/BANNER/g5dqzcs4zwgxvvw3lsma.jpg"
                        },
                        new
                        {
                            MovieMediaId = 15,
                            MovieId = 4,
                            Name = "The Dark Knight Trailer",
                            PublicId = "TRAILER/kou9a1hm4axazrmvxfgh",
                            Type = 4,
                            Url = "https://res.cloudinary.com/dl3zwdtki/video/upload/v1719775117/TRAILER/kou9a1hm4axazrmvxfgh.mp4"
                        },
                        new
                        {
                            MovieMediaId = 16,
                            MovieId = 4,
                            Name = "The Dark Knight Video",
                            PublicId = "VIDEO/fnoqi8bubpp3zk2l44y5",
                            Type = 6,
                            Url = "https://res.cloudinary.com/dl3zwdtki/video/upload/v1719775341/VIDEO/fnoqi8bubpp3zk2l44y5.mp4"
                        },
                        new
                        {
                            MovieMediaId = 17,
                            MovieId = 5,
                            Name = "Avatar Poster",
                            PublicId = "POSTER/xhprcuwrw5rewdojm9ke",
                            Type = 2,
                            Url = "https://res.cloudinary.com/dl3zwdtki/image/upload/v1722168426/POSTER/p6ixrrzrgzoywdhmbarj.jpg"
                        },
                        new
                        {
                            MovieMediaId = 18,
                            MovieId = 5,
                            Name = "Avatar Banner",
                            PublicId = "BANNER/g5dqzcs4zwgxvvw3lsma",
                            Type = 3,
                            Url = "https://res.cloudinary.com/dl3zwdtki/image/upload/v1719774957/BANNER/g5dqzcs4zwgxvvw3lsma.jpg"
                        },
                        new
                        {
                            MovieMediaId = 19,
                            MovieId = 5,
                            Name = "Avatar Trailer",
                            PublicId = "TRAILER/kou9a1hm4axazrmvxfgh",
                            Type = 4,
                            Url = "https://res.cloudinary.com/dl3zwdtki/video/upload/v1719775117/TRAILER/kou9a1hm4axazrmvxfgh.mp4"
                        },
                        new
                        {
                            MovieMediaId = 20,
                            MovieId = 5,
                            Name = "Avatar Video",
                            PublicId = "VIDEO/fnoqi8bubpp3zk2l44y5",
                            Type = 6,
                            Url = "https://res.cloudinary.com/dl3zwdtki/video/upload/v1719775341/VIDEO/fnoqi8bubpp3zk2l44y5.mp4"
                        },
                        new
                        {
                            MovieMediaId = 21,
                            MovieId = 6,
                            Name = "The Matrix Poster",
                            PublicId = "POSTER/xhprcuwrw5rewdojm9ke",
                            Type = 2,
                            Url = "https://res.cloudinary.com/dl3zwdtki/image/upload/v1722168426/POSTER/p6ixrrzrgzoywdhmbarj.jpg"
                        },
                        new
                        {
                            MovieMediaId = 22,
                            MovieId = 6,
                            Name = "The Matrix Banner",
                            PublicId = "BANNER/g5dqzcs4zwgxvvw3lsma",
                            Type = 3,
                            Url = "https://res.cloudinary.com/dl3zwdtki/image/upload/v1719774957/BANNER/g5dqzcs4zwgxvvw3lsma.jpg"
                        },
                        new
                        {
                            MovieMediaId = 23,
                            MovieId = 6,
                            Name = "The Matrix Trailer",
                            PublicId = "TRAILER/kou9a1hm4axazrmvxfgh",
                            Type = 4,
                            Url = "https://res.cloudinary.com/dl3zwdtki/video/upload/v1719775117/TRAILER/kou9a1hm4axazrmvxfgh.mp4"
                        },
                        new
                        {
                            MovieMediaId = 24,
                            MovieId = 6,
                            Name = "The Matrix Video",
                            PublicId = "VIDEO/fnoqi8bubpp3zk2l44y5",
                            Type = 6,
                            Url = "https://res.cloudinary.com/dl3zwdtki/video/upload/v1719775341/VIDEO/fnoqi8bubpp3zk2l44y5.mp4"
                        },
                        new
                        {
                            MovieMediaId = 25,
                            MovieId = 7,
                            Name = "La La Land Poster",
                            PublicId = "POSTER/xhprcuwrw5rewdojm9ke",
                            Type = 2,
                            Url = "https://res.cloudinary.com/dl3zwdtki/image/upload/v1722168426/POSTER/p6ixrrzrgzoywdhmbarj.jpg"
                        },
                        new
                        {
                            MovieMediaId = 26,
                            MovieId = 7,
                            Name = "La La Land Banner",
                            PublicId = "BANNER/g5dqzcs4zwgxvvw3lsma",
                            Type = 3,
                            Url = "https://res.cloudinary.com/dl3zwdtki/image/upload/v1719774957/BANNER/g5dqzcs4zwgxvvw3lsma.jpg"
                        },
                        new
                        {
                            MovieMediaId = 27,
                            MovieId = 7,
                            Name = "La La Land Trailer",
                            PublicId = "TRAILER/kou9a1hm4axazrmvxfgh",
                            Type = 4,
                            Url = "https://res.cloudinary.com/dl3zwdtki/video/upload/v1719775117/TRAILER/kou9a1hm4axazrmvxfgh.mp4"
                        },
                        new
                        {
                            MovieMediaId = 28,
                            MovieId = 7,
                            Name = "La La Land Video",
                            PublicId = "VIDEO/fnoqi8bubpp3zk2l44y5",
                            Type = 6,
                            Url = "https://res.cloudinary.com/dl3zwdtki/video/upload/v1719775341/VIDEO/fnoqi8bubpp3zk2l44y5.mp4"
                        },
                        new
                        {
                            MovieMediaId = 29,
                            MovieId = 8,
                            Name = "The Lord of the Rings: The Return of the King Poster",
                            PublicId = "POSTER/xhprcuwrw5rewdojm9ke",
                            Type = 2,
                            Url = "https://res.cloudinary.com/dl3zwdtki/image/upload/v1722168426/POSTER/p6ixrrzrgzoywdhmbarj.jpg"
                        },
                        new
                        {
                            MovieMediaId = 30,
                            MovieId = 8,
                            Name = "The Lord of the Rings: The Return of the King Banner",
                            PublicId = "BANNER/g5dqzcs4zwgxvvw3lsma",
                            Type = 3,
                            Url = "https://res.cloudinary.com/dl3zwdtki/image/upload/v1719774957/BANNER/g5dqzcs4zwgxvvw3lsma.jpg"
                        },
                        new
                        {
                            MovieMediaId = 31,
                            MovieId = 8,
                            Name = "The Lord of the Rings: The Return of the King Trailer",
                            PublicId = "TRAILER/kou9a1hm4axazrmvxfgh",
                            Type = 4,
                            Url = "https://res.cloudinary.com/dl3zwdtki/video/upload/v1719775117/TRAILER/kou9a1hm4axazrmvxfgh.mp4"
                        },
                        new
                        {
                            MovieMediaId = 32,
                            MovieId = 8,
                            Name = "The Lord of the Rings: The Return of the King Video",
                            PublicId = "VIDEO/fnoqi8bubpp3zk2l44y5",
                            Type = 6,
                            Url = "https://res.cloudinary.com/dl3zwdtki/video/upload/v1719775341/VIDEO/fnoqi8bubpp3zk2l44y5.mp4"
                        },
                        new
                        {
                            MovieMediaId = 33,
                            MovieId = 9,
                            Name = "Pan's Labyrinth Poster",
                            PublicId = "POSTER/xhprcuwrw5rewdojm9ke",
                            Type = 2,
                            Url = "https://res.cloudinary.com/dl3zwdtki/image/upload/v1722168426/POSTER/p6ixrrzrgzoywdhmbarj.jpg"
                        },
                        new
                        {
                            MovieMediaId = 34,
                            MovieId = 9,
                            Name = "Pan's Labyrinth Banner",
                            PublicId = "BANNER/g5dqzcs4zwgxvvw3lsma",
                            Type = 3,
                            Url = "https://res.cloudinary.com/dl3zwdtki/image/upload/v1719774957/BANNER/g5dqzcs4zwgxvvw3lsma.jpg"
                        },
                        new
                        {
                            MovieMediaId = 35,
                            MovieId = 9,
                            Name = "Pan's Labyrinth Trailer",
                            PublicId = "TRAILER/kou9a1hm4axazrmvxfgh",
                            Type = 4,
                            Url = "https://res.cloudinary.com/dl3zwdtki/video/upload/v1719775117/TRAILER/kou9a1hm4axazrmvxfgh.mp4"
                        },
                        new
                        {
                            MovieMediaId = 36,
                            MovieId = 9,
                            Name = "Pan's Labyrinth Video",
                            PublicId = "VIDEO/fnoqi8bubpp3zk2l44y5",
                            Type = 6,
                            Url = "https://res.cloudinary.com/dl3zwdtki/video/upload/v1719775341/VIDEO/fnoqi8bubpp3zk2l44y5.mp4"
                        },
                        new
                        {
                            MovieMediaId = 37,
                            MovieId = 10,
                            Name = "Wonder Woman Poster",
                            PublicId = "POSTER/xhprcuwrw5rewdojm9ke",
                            Type = 2,
                            Url = "https://res.cloudinary.com/dl3zwdtki/image/upload/v1722168426/POSTER/p6ixrrzrgzoywdhmbarj.jpg"
                        },
                        new
                        {
                            MovieMediaId = 38,
                            MovieId = 10,
                            Name = "Wonder Woman Banner",
                            PublicId = "BANNER/g5dqzcs4zwgxvvw3lsma",
                            Type = 3,
                            Url = "https://res.cloudinary.com/dl3zwdtki/image/upload/v1719774957/BANNER/g5dqzcs4zwgxvvw3lsma.jpg"
                        },
                        new
                        {
                            MovieMediaId = 39,
                            MovieId = 10,
                            Name = "Wonder Woman Trailer",
                            PublicId = "TRAILER/kou9a1hm4axazrmvxfgh",
                            Type = 4,
                            Url = "https://res.cloudinary.com/dl3zwdtki/video/upload/v1719775117/TRAILER/kou9a1hm4axazrmvxfgh.mp4"
                        },
                        new
                        {
                            MovieMediaId = 40,
                            MovieId = 10,
                            Name = "Wonder Woman Video",
                            PublicId = "VIDEO/fnoqi8bubpp3zk2l44y5",
                            Type = 6,
                            Url = "https://res.cloudinary.com/dl3zwdtki/video/upload/v1719775341/VIDEO/fnoqi8bubpp3zk2l44y5.mp4"
                        });
                });

            modelBuilder.Entity("Sever.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            RoleId = 1,
                            Name = "Admin"
                        },
                        new
                        {
                            RoleId = 2,
                            Name = "Member"
                        },
                        new
                        {
                            RoleId = 5,
                            Name = "Guest"
                        });
                });

            modelBuilder.Entity("Sever.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("UserId"), 1L, 1);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePicture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            DateCreated = new DateTime(2024, 8, 7, 20, 7, 6, 490, DateTimeKind.Local).AddTicks(1599),
                            DateUpdated = new DateTime(2024, 8, 7, 20, 7, 6, 490, DateTimeKind.Local).AddTicks(1725),
                            Email = "admin@gmail.com",
                            FirstName = "Admin",
                            LastName = "First",
                            Password = "AQAAAAEAACcQAAAAELdGQqVyvb3J9xiEQQ6tqWdBbLF8gX1FoQarO6cjEu9O7noO5dx/LJLXbxch3w/xOw==",
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("Sever.Models.WatchList", b =>
                {
                    b.Property<int>("WatchListId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WatchListId"), 1L, 1);

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateUpdated")
                        .HasColumnType("datetime2");

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("WatchListId");

                    b.HasIndex("MovieId");

                    b.HasIndex("UserId");

                    b.ToTable("WatchLists");
                });

            modelBuilder.Entity("Sever.Models.Movie", b =>
                {
                    b.HasOne("Sever.Models.Director", "Director")
                        .WithMany("Movies")
                        .HasForeignKey("DirectorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sever.Models.Genre", "Genre")
                        .WithMany("Movies")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Director");

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("Sever.Models.MovieActor", b =>
                {
                    b.HasOne("Sever.Models.Actor", "Actor")
                        .WithMany("MovieActors")
                        .HasForeignKey("ActorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sever.Models.Movie", "Movie")
                        .WithMany("MovieActors")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Actor");

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("Sever.Models.MovieMedia", b =>
                {
                    b.HasOne("Sever.Models.Movie", "Movie")
                        .WithMany("MovieMedias")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");
                });

            modelBuilder.Entity("Sever.Models.User", b =>
                {
                    b.HasOne("Sever.Models.Role", "Role")
                        .WithMany("Users")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Sever.Models.WatchList", b =>
                {
                    b.HasOne("Sever.Models.Movie", "Movie")
                        .WithMany("WatchLists")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Sever.Models.User", "User")
                        .WithMany("WatchLists")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Movie");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Sever.Models.Actor", b =>
                {
                    b.Navigation("MovieActors");
                });

            modelBuilder.Entity("Sever.Models.Director", b =>
                {
                    b.Navigation("Movies");
                });

            modelBuilder.Entity("Sever.Models.Genre", b =>
                {
                    b.Navigation("Movies");
                });

            modelBuilder.Entity("Sever.Models.Movie", b =>
                {
                    b.Navigation("MovieActors");

                    b.Navigation("MovieMedias");

                    b.Navigation("WatchLists");
                });

            modelBuilder.Entity("Sever.Models.Role", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("Sever.Models.User", b =>
                {
                    b.Navigation("WatchLists");
                });
#pragma warning restore 612, 618
        }
    }
}
